language: c

# compilers wanted
compiler:
  - gcc

# command to install dependencies
#   candy_makefile/ uses python
#   src_daemon/ is tested with pytest
install:
  - "sudo apt-get install python"
  - "sudo apt-get install python-pip"
  - "sudo pip install pytest"

# command to run tests
script: "make hook"
