language: c

# compilers wanted
compiler:
  - gcc

# command to install dependencies
#   candy_makefile/ uses python
#   src_daemon/ is tested with pytest
install:
  - "apt-get install python-2.7"
  - "apt-get install python-pip"
  - "pip install pytest"

# command to run tests
script: "make hook"
